apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: games-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: games-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
